limelight/api/blueprint.py
from flask import Blueprint, jsonify

from ..crud import create_project, find_project
from ..forms import NewProjectForm
from ..limiter import limiter

blueprint = Blueprint("api", __name__)


@blueprint.post("/new-project/")
@limiter.limit("1 per minute")
def new_project():
    form = NewProjectForm()
    if form.validate_on_submit():
        if project := find_project(form.data["slug"]):
            return jsonify(project), 200
        new_project = create_project(form.data, True)
        return jsonify({"slug": new_project.slug}), 201
    return jsonify(form.errors), 400

limelight/website/blueprint.py
from flask import Blueprint, Response, redirect, render_template, url_for
from sqlalchemy import desc

from ..crud import add_queue, get_new_data, get_old_data, process_queue_item
from ..database import db
from ..forms import NewProjectForm
from ..models import Project, Tag
from ..sitemap import sitemapper
from ..utils import full_update_project_metadata

blueprint = Blueprint("website", __name__)


# Queue Manager
@blueprint.before_request
def find_new_projects():
    queue_types = {1: "pypi", 2: "git", 4: "downloads"}

    for queue_type, _name in queue_types.items():
        if data := get_new_data(queue_type=queue_type):
            add_queue(project=data, project_type=queue_type)


@blueprint.before_request
def find_old_projects():
    queue_types = {1: "pypi", 2: "git", 4: "downloads"}
    days = 7

    for queue_type, _name in queue_types.items():
        if old_data := get_old_data(days=days, queue_type=queue_type):
            add_queue(project=old_data, project_type=queue_type)


@blueprint.before_request
def queue_item():
    process_queue_item()


@sitemapper.include(
    priority=1.0,
    changefreq="daily",
)
@blueprint.get("/")
def home():
    featured_tags = db.session.execute(db.select(Tag).where(Tag.feature_in_home).order_by(Tag.order_in_home)).all()
    projects = db.session.execute(db.select(Project).order_by(desc(Project.id)).limit(5)).all()
    releases = db.session.execute(db.select(Project).order_by(desc(Project.last_release_date)).limit(5)).all()
    return render_template(
        "website/landing.html",
        featured_tags=featured_tags,
        projects=projects,
        releases=releases,
    )


@sitemapper.include(
    priority=0.8,
    changefreq="yearly",
)
@blueprint.get("/help/")
def help():
    return render_template("website/help.html")


@sitemapper.include(
    priority=0.6,
    changefreq="weekly",
    url_variables={
        "project_type": ["framework", "extension", "module", "project"],
    },
)
@blueprint.get("/<any(framework,extension,module,project,fulllist):project_type>/")
def projects(project_type):
    if project_type == "fulllist":
        projects = db.session.execute(db.select(Project)).all()
    else:
        projects = db.session.execute(db.select(Project).where(Project.category == project_type)).all()

    return render_template(
        "website/project_list.html",
        project_type=project_type,
        projects=projects,
    )


@sitemapper.include(
    priority=0.6,
    changefreq="weekly",
    url_variables={
        "slug": ["flask", "quart"],
    },
)
@blueprint.get("/about/<any(flask,quart):slug>/")
def get_project_info(slug):
    project = db.first_or_404(db.select(Project).where(Project.slug == slug))
    project = full_update_project_metadata(project=project)
    return render_template(f"website/{slug}_info.html", project=project)


@blueprint.get("/project/<slug>")
def get_project(slug):
    if slug in ["flask", "quart"]:
        return redirect(url_for("website.get_project_info", slug=slug), code=301)
    project = db.first_or_404(db.select(Project).where(Project.slug == slug))
    project = full_update_project_metadata(project=project)
    return render_template("website/project.html", project=project)


@sitemapper.include(
    priority=0.6,
    changefreq="weekly",
    url_variables={
        "slug": ["auth", "database", "api", "forms", "security", "frontend", "developer-tools"],
    },
)
@blueprint.get("/category/<slug>")
def get_tag(slug):
    tag = db.first_or_404(db.select(Tag).where(Tag.slug == slug))
    return render_template("website/tag.html", tag=tag)


@sitemapper.include(
    priority=1.0,
    changefreq="monthly",
)
@blueprint.route("/new-project/", methods=["GET"])
def new_project():
    form = NewProjectForm()
    return render_template("website/new_project.html", form=form)


@blueprint.route("/robots.txt", methods=["GET"])
def robok():
    robots = render_template("robots.txt")
    return Response(robots, mimetype="text/plain")


@blueprint.get("/sitemap.xml")
def full_sitemap():
    return sitemapper.generate()


@blueprint.get("/sitemap-projects.xml")
def project_sitemap():
    projects = db.session.execute(db.select(Project)).all()
    sitemap = render_template("sitemap.xml", projects=projects)
    return Response(sitemap, mimetype="application/xml")


@blueprint.get("tyn4pbqky6nwdz36cm33m343uga1pqv7.txt")
def index_now():
    return "tyn4pbqky6nwdz36cm33m343uga1pqv7"

limelight/templates/website/flask_info.html
{% extends "main.html" %}

{% block content %}
<!-- Hero Section -->
<section class="bg-primary text-white text-center py-5">
  <div class="container">
    <h1>Flask</h1>
    <p></p>
  </div>
</section>

<section class="py-5 bg-light">
  <div class="container">
    <div class="row featurette">
      <div class="col-md-12">
        <h2 class="featurette-heading fw-normal lh-1">Want to help? <span class="text-body-secondary">Here's how...</span></h2>
        <p class="lead">You can always check the <a href="https://github.com/mariofix/limelight" target="_blank">source code</a> for this project, The following is currently needed to have the "first proper version":</p>
        <ul>
          <li><strong>Opinions</strong>: Your opinion is very important to me, if you have suggestions, ideas, complaints, <a href="https://github.com/mariofix/limelight/discussions/new?category=general" target="_blank">they are all very welcomed.</a></li>
          <li><strong>Information Gathering&Filtering</strong>: There are about <a href="https://pypi.org/search/?q=flask" target="_blank">8000 projects in pypi</a>, just add the slug and the system will do the rest, but there is so much the system can guess, so you can also modify the <a href="#">project's metadata</a> so the crawler can work next time.</li>
          <li><strong>Front-End</strong>: As you can see, Visual Design is not my strong suit, ANY help in this topic is very much appreciated, <a href="https://github.com/mariofix/limelight/pull" target="_blank">just send a PR.</a></li>
          <li><strong>Infra&SEO</strong>: The app is currently in the free tier of pythonanywhere, I intend to pay as the traffic demands it but another domain name or subdomain will be nice, and in kind of the same topic, suggestions on how to make the domain migration without suffering in the search engines.</li>
          <li><strong>Pass the word</strong>: Just pass the word, this is the best thing you can do to help.</li>
        </ul>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

limelight/templates/website/help.html
{% extends "main.html" %}

{% block content %}
<!-- Hero Section -->
<section class="bg-primary text-white text-center py-5">
  <div class="container">
    <h1>Discover Open Source Flask Extensions</h1>
    <p>Community-Driven Development for Flask Enthusiasts</p>
    <div>
      <a href="{{ url_for('website.new_project') }}" class="btn btn-light btn-lg">Contribute Project</a>
      <a href="{{ url_for('website.projects', project_type='project') }}" class="btn btn-outline-light btn-lg">Browse Projects</a>
    </div>
  </div>
</section>

<section class="py-5 bg-light">
  <div class="container">
    <div class="row featurette">
      <div class="col-md-12">
        <h2 class="featurette-heading fw-normal lh-1">Want to help? <span class="text-body-secondary">Here's how...</span></h2>
        <p class="lead">You can always check the <a href="https://github.com/mariofix/limelight" target="_blank">source code</a> for this project, The following is currently needed to have the "first proper version":</p>
        <ul>
          <li><strong>Opinions</strong>: Your opinion is very important to me, if you have suggestions, ideas, complaints, <a href="https://github.com/mariofix/limelight/discussions/new?category=general" target="_blank">they are all very welcomed.</a></li>
          <li><strong>Information Gathering&Filtering</strong>: There are about <a href="https://pypi.org/search/?q=flask" target="_blank">8000 projects in pypi</a>, just add the slug and the system will do the rest, but there is so much the system can guess, so you can also modify the <a href="#">project's metadata</a> so the crawler can work next time.</li>
          <li><strong>Front-End</strong>: As you can see, Visual Design is not my strong suit, ANY help in this topic is very much appreciated, <a href="https://github.com/mariofix/limelight/pull" target="_blank">just send a PR.</a></li>
          <li><strong>Infra&SEO</strong>: The app is currently in the free tier of pythonanywhere, I intend to pay as the traffic demands it but another domain name or subdomain will be nice, and in kind of the same topic, suggestions on how to make the domain migration without suffering in the search engines.</li>
          <li><strong>Pass the word</strong>: Just pass the word, this is the best thing you can do to help.</li>
        </ul>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

limelight/templates/website/landing.html
{% extends "main.html" %}

{% block content %}
<!-- Hero Section -->
<section class="bg-primary text-white text-center py-5">
  <div class="container">
    <h1>Discover Open Source Flask Extensions</h1>
    <p>Community-Driven Development for Flask Enthusiasts</p>
    <div>
      <a href="{{ url_for('website.new_project') }}" class="btn btn-light btn-lg">Contribute Project</a>
      <a href="{{ url_for('website.projects', project_type='fulllist') }}" class="btn btn-outline-light btn-lg">Browse Projects</a>
    </div>
  </div>
</section>
<!-- Common Scenarios Section -->
<section class="py-5 bg-light">
  <div class="container">
    <div class="row text-center">
      {% for tag in featured_tags %}
      <div class="col-md-4 mb-3">
        <a href="{{ url_for('website.get_tag', slug=tag[0].slug) }}" class="card shadow-sm text-decoration-none">
          <div class="card-body">
            <i class="{{ tag[0].icon}}" style="font-size: 2rem; color: var(--primary)"></i>
            <h5 class="card-title mt-2">{{ tag[0].title }}</h5>
            <p class="text-muted">{{ tag[0].description }}</p>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<!-- Latest Inclusions and Top Extensions Section -->
<section class="py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card h-100">
          <div class="card-header bg-success text-white">
            <h5 class="mb-0">Latest Projects</h5>
          </div>
          <div class="card-body">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Category</th>
                  <th>Created</th>
                </tr>
              </thead>
              <tbody>
                {% for p in projects %}
                <tr>
                  <td><a href="{{ url_for('website.get_project', slug=p[0].slug) }}">{{ p[0].title }}</a></td>
                  <td><a href="{{ url_for('website.get_tag', slug=p[0].tags[0]) }}">{{ p[0].tags[0]|capitalize }}</a></td>
                  <td>{{ p[0].date_last( 'first_release_date' ) }}</td>
                </tr>
                {% endfor%}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card h-100">
          <div class="card-header bg-success text-white">
            <h5 class="mb-0">Latest Releases</h5>
          </div>
          <div class="card-body">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Version</th>
                  <th>When</th>
                </tr>
              </thead>
              <tbody>
                {% for r in releases %}
                <tr>
                  <td><a href="{{ url_for('website.get_project', slug=r[0].slug) }}">{{ r[0].title }}</a></td>
                  <td>{{ r[0].last_release }}</td>
                  <td>{{ r[0].date_last( 'last_release_date' ) }}</td>
                </tr>
                {% endfor%}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="py-5 bg-light">
  <div class="container">
    <div class="row featurette">
      <div class="col-md-12">
        <h2 class="featurette-heading fw-normal lh-1">Want to help? <span class="text-body-secondary">Here's how...</span></h2>
        <p class="lead">You can always check the <a href="https://github.com/mariofix/limelight" target="_blank">source code</a> for this project, The following is currently needed to have the "first proper version":</p>
        <ul>
          <li><strong>Opinions</strong>: Your opinion is very important to me, if you have suggestions, ideas, complaints, <a href="https://github.com/mariofix/limelight/discussions/new?category=general" target="_blank">they are all very welcomed.</a></li>
          <li><strong>Information Gathering&Filtering</strong>: There are about <a href="https://pypi.org/search/?q=flask" target="_blank">8000 projects in pypi</a>, just add the slug and the system will do the rest, but there is so much the system can guess, so you can also modify the <a href="#">project's metadata</a> so the crawler can work next time.</li>
          <li><strong>Front-End</strong>: As you can see, Visual Design is not my strong suit, ANY help in this topic is very much appreciated, <a href="https://github.com/mariofix/limelight/pull" target="_blank">just send a PR.</a></li>
          <li><strong>Infra&SEO</strong>: The app is currently in the free tier of pythonanywhere, I intend to pay as the traffic demands it but another domain name or subdomain will be nice, and in kind of the same topic, suggestions on how to make the domain migration without suffering in the search engines.</li>
          <li><strong>Pass the word</strong>: Just pass the word, this is the best thing you can do to help.</li>
        </ul>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

limelight/templates/website/new_project.html
{% extends "main.html" %}

{% block content %}
<!-- Hero Section -->
<section class="bg-primary text-white text-center py-5">
  <div class="container">
    <h1>New Project</h1>
    <p>Let us know a project we don't have.</p>
  </div>
</section>

<!-- Add Project Section -->
<section class="container py-5">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <!-- PyPI Card -->
    <div class="col">
      <div class="card h-100 text-center">
        <div class="card-body">
          <i class="bi bi-boxes display-4 text-primary mb-3"></i>
          <h5 class="card-title">Add from PyPI</h5>
          <p class="card-text">Fetch Python project details using its PyPI slug.</p>
          <form onsubmit="handleSubmit(event, 'pypi')">
            <div class="input-group">
              <span class="input-group-text" id="addon-wrapping"><i class="bi bi-boxes"></i></span>
              <input type="text" class="form-control" id="pypiSlug" placeholder="project-slug" required>
              <button type="submit" class="btn btn-secondary">Add</button>
            </div>
            <div class="valid-feedback">Project successfully added!</div>
            <div class="invalid-feedback">Something went wrong. Please try again.</div>
          </form>

        </div>
      </div>
    </div>
    <!-- Anaconda Card -->
    <div class="col">
      <div class="card h-100 text-center">
        <div class="card-body">
          <i class="bi bi-c-circle display-4 text-success mb-3"></i>
          <h5 class="card-title">Add from Anaconda</h5>
          <p class="card-text">Fetch project details using its Anaconda slug.</p>

          <form onsubmit="handleSubmit(event, 'anaconda')">
            <div class="input-group">
              <span class="input-group-text" id="addon-wrapping"><i class="bi bi-c-circle"></i></span>
              <input type="text" class="form-control" id="anacondaSlug" placeholder="channel/project-slug" required>
              <button type="submit" class="btn btn-secondary">Add</button>
            </div>
            <div class="valid-feedback">Project successfully added!</div>
            <div class="invalid-feedback">Something went wrong. Please try again.</div>
          </form>

        </div>
      </div>
    </div>
    <!-- Other Sources Card -->
    <div class="col">
      <div class="card h-100 text-center">
        <div class="card-body">
          <i class="bi bi-globe display-4 text-secondary mb-3"></i>
          <h5 class="card-title">Add from Other Sources</h5>
          <p class="card-text">Add a project from any git repository.</p>

          <form onsubmit="handleSubmit(event, 'git')">
            <div class="input-group">
              <span class="input-group-text" id="addon-wrapping"><i class="bi bi-globe"></i></span>
              <input type="url" class="form-control" id="gitRepo" placeholder="https://github.com/user/repo.git" required>
              <button type="submit" class="btn btn-secondary">Add</button>
            </div>
            <div class="valid-feedback">Project successfully added!</div>
            <div class="invalid-feedback">Something went wrong. Please try again.</div>
          </form>

        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

{% block post_js %}
<script type="text/javascript">
  function handleSubmit(event, origin) {
    event.preventDefault();
    const form = event.target;
    const slugInput = form.querySelector('input');
    const button = form.querySelector('button[type="submit"]');

    const slug = slugInput.value;
    const payload = { "slug": slug, "origen": origin, "csrf_token": "{{ form.csrf_token._value() }}" };

    fetch('{{ url_for("api.new_project") }}', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(payload),
    })
      .then((response) => {
        const url = "{{ url_for('website.get_project', slug='1') }}";
        if (response.status === 200) {
          window.location.href = url.replace("1", payload.slug);
        } else if (response.status === 201) {
          window.location.href = url.replace("1", payload.slug);
        } else {
          button.classList.remove('btn-primary', 'btn-info', 'btn-success');
          button.classList.add('btn-danger');
          form.classList.remove('is-valid');
          form.classList.add('is-invalid');
          form.querySelector('.invalid-feedback').textContent = 'An error occurred. Please try again.';
        }
      })
      .catch(() => {
        button.classList.remove('btn-primary', 'btn-info', 'btn-success');
        button.classList.add('btn-danger');
        form.classList.remove('is-valid');
        form.classList.add('is-invalid');
        form.querySelector('.invalid-feedback').textContent = 'An error occurred. Please try again.';
      });
  }


</script>
{% endblock post_js %}

limelight/templates/website/project_list.html
{% extends "main.html" %}
{% block meta_content %}
<meta name="description" content="Registered extensions under {{project_type}}">
<meta name="robots" content="index, follow">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="author" content="mariofix">
<meta name="language" content="English">
<meta name="revisit-after" content="7 days">
<link rel="canonical" href="https://flaskpackages.pythonanywhere.com/{{ project_type }}/">
<meta property="og:title" content="{{ project_type|capitalize }}s">
<meta property="og:site_name" content="Flask Packages">
<meta property="og:url" content="https://flaskpackages.pythonanywhere.com/{{ project_type }}/">
<meta property="og:description" content="Registered extensions under {{project_type}}">
<meta property="og:type" content="website">

{% endblock meta_content %}
{% block content %}
<section class="bg-primary text-white text-center py-5">
  <div class="container">

    <h1>Registered Extensions{% if project_type != "fulllist"  %} - {{ project_type|capitalize }}s{% endif %}</h1>

  </div>
</section>

<div class="py-5 bg-body-tertiary">
  <div class="container">
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th>Project</th>
            <th>Current Release</th>
            <th>Python Compatibility</th>
            <th>Flask Compatibility</th>
            <th>Downloads</th>
            <th>Open Issues</th>
            <th>Subscribers</th>
            <th>Last Crawl</th>
          </tr>
        </thead>
        <tbody>
          {% for project in projects %}
          <tr>
            <td><a href="{{ url_for('website.get_project', slug=project[0].slug) }}">{{ project[0].slug }}</a></td>
            <td><span class="d-inline-flex px-2 py-1 fw-semibold text-success-emphasis bg-success-subtle border border-success-subtle rounded-2">{{ project[0].last_release }}</span> <span class="text-secondary small">{{ project[0].date_last('last_release_date') }}</span></td>
            <td style="word-wrap: break-word;min-width: 50px;max-width: 50px;">{{ project[0].supported_python|default("Not Found", boolean=true) }}</td>
            <td style="word-wrap: break-word;min-width: 50px;max-width: 50px;">{{ project[0].supported_flask|default("Any version", boolean=true) }}</td>
            <td>{{ project[0].downloads|default(0, boolean=True)|humanize_intword|replace("billion","B")|replace("million","M")|replace("thousand","K") }}</td>
            <td>{{ project[0].issues_open|default("0", boolean=true) }}</td>
            <td>{{ project[0].subscribers|default("0", boolean=true) }}</td>
            <td><span class="text-secondary small">{{ project[0].date_last('pypi_data_date') }}</span></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    </div>
  </div>
</div>
{% endblock content %}

limelight/templates/website/quart_info.html
{% extends "main.html" %}

{% block content %}
<!-- Hero Section -->
<section class="bg-primary text-white text-center py-5">
  <div class="container">
    <h1>Quart</h1>
    <p></p>
  </div>
</section>

<section class="py-5 bg-light">
  <div class="container">
    <div class="row featurette">
      <div class="col-md-12">
        <h2 class="featurette-heading fw-normal lh-1">Want to help? <span class="text-body-secondary">Here's how...</span></h2>
        <p class="lead">You can always check the <a href="https://github.com/mariofix/limelight" target="_blank">source code</a> for this project, The following is currently needed to have the "first proper version":</p>
        <ul>
          <li><strong>Opinions</strong>: Your opinion is very important to me, if you have suggestions, ideas, complaints, <a href="https://github.com/mariofix/limelight/discussions/new?category=general" target="_blank">they are all very welcomed.</a></li>
          <li><strong>Information Gathering&Filtering</strong>: There are about <a href="https://pypi.org/search/?q=flask" target="_blank">8000 projects in pypi</a>, just add the slug and the system will do the rest, but there is so much the system can guess, so you can also modify the <a href="#">project's metadata</a> so the crawler can work next time.</li>
          <li><strong>Front-End</strong>: As you can see, Visual Design is not my strong suit, ANY help in this topic is very much appreciated, <a href="https://github.com/mariofix/limelight/pull" target="_blank">just send a PR.</a></li>
          <li><strong>Infra&SEO</strong>: The app is currently in the free tier of pythonanywhere, I intend to pay as the traffic demands it but another domain name or subdomain will be nice, and in kind of the same topic, suggestions on how to make the domain migration without suffering in the search engines.</li>
          <li><strong>Pass the word</strong>: Just pass the word, this is the best thing you can do to help.</li>
        </ul>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

limelight/templates/website/tag.html
{% extends "main.html" %}

{% block title%}{{ tag.title }} - Flask Packages{% endblock title %}

{% block meta_content %}
<meta name="description" content="{{ tag.description }}">
<meta name="robots" content="index, follow">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="author" content="{{ tag.title }}">
<meta name="language" content="English">
<meta name="revisit-after" content="7 days">
<link rel="canonical" href="https://flaskpackages.pythonanywhere.com/category/{{ tag.slug }}/">
<meta property="og:title" content="{{ tag.title }}">
<meta property="og:site_name" content="Flask Packages">
<meta property="og:url" content="https://flaskpackages.pythonanywhere.com/category/{{ tag.slug }}/">
<meta property="og:description" content="{{ tag.description }}">
<meta property="og:type" content="website">

{% endblock meta_content %}

{% block content %}
<section class="py-5 bg-light">
  <div class="container">
    <!-- Header Section -->
    <div class="d-flex justify-content-between align-items-center mb-4">
      <div>
        <h1 class="h3 mb-0">{{ tag.title }} </h1>
        <p class="text-muted small mb-0">{{ tag.description }}</p>
      </div>
    </div>
  </div>
</section>

<div class="bg-body-tertiary">
  <div class="container">
    <div class="row">
      <table class="table">
        <thead>
          <tr>
            <th>Project</th>
            <th>Current Release</th>
            <th>Python Compatibility</th>
            <th>Flask Compatibility</th>
            <th>Downloads</th>
            <th>Open Issues</th>
            <th>Subscribers</th>
            <th>Last Crawl</th>
          </tr>
        </thead>
        <tbody>
          {% for project in tag.projects %}
          <tr>
            <td><a href="{{ url_for('website.get_project', slug=project.slug) }}">{{ project.slug }}</a></td>
            <td><span class="d-inline-flex px-2 py-1 fw-semibold text-success-emphasis bg-success-subtle border border-success-subtle rounded-2">{{ project.last_release }}</span> <span class="text-secondary small">{{ project.date_last('last_release_date') }}</span></td>
            <td style="word-wrap: break-word;min-width: 50px;max-width: 50px;">{{ project.supported_python|default("Not Found", boolean=true) }}</td>
            <td style="word-wrap: break-word;min-width: 50px;max-width: 50px;">{{ project.supported_flask|default("Any version", boolean=true) }}</td>
            <td>{{ project.downloads|default(0, boolean=True)|humanize_intword|replace("billion","B")|replace("million","M")|replace("thousand","K") }}</td>
            <td>{{ project.issues_open|default("0", boolean=true) }}</td>
            <td>{{ project.subscribers|default("0", boolean=true) }}</td>
            <td><span class="text-secondary small">{{ project.date_last('pypi_data_date') }}</span></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    </div>
  </div>
</div>


{% endblock content %}