limelight/website/blueprint.py
from flask import Blueprint, Response, redirect, render_template, url_for
from sqlalchemy import desc

from ..crud import add_queue, get_new_data, get_old_data, process_queue_item
from ..database import db
from ..forms import NewProjectForm
from ..models import Project, Tag
from ..sitemap import sitemapper
from ..utils import full_update_project_metadata

blueprint = Blueprint("website", __name__)


# Queue Manager
@blueprint.before_request
def find_new_projects():
    queue_types = {1: "pypi", 2: "git", 4: "downloads"}

    for queue_type, _name in queue_types.items():
        if data := get_new_data(queue_type=queue_type):
            add_queue(project=data, project_type=queue_type)


@blueprint.before_request
def find_old_projects():
    queue_types = {1: "pypi", 2: "git", 4: "downloads"}
    days = 7

    for queue_type, _name in queue_types.items():
        if old_data := get_old_data(days=days, queue_type=queue_type):
            add_queue(project=old_data, project_type=queue_type)


@blueprint.before_request
def queue_item():
    process_queue_item()


@sitemapper.include(
    priority=1.0,
    changefreq="daily",
)
@blueprint.get("/")
def home():
    featured_tags = db.session.execute(db.select(Tag).where(Tag.feature_in_home).order_by(Tag.order_in_home)).all()
    projects = db.session.execute(db.select(Project).order_by(desc(Project.id)).limit(5)).all()
    releases = db.session.execute(db.select(Project).order_by(desc(Project.last_release_date)).limit(5)).all()
    return render_template(
        "website/landing.html",
        featured_tags=featured_tags,
        projects=projects,
        releases=releases,
    )


@sitemapper.include(
    priority=0.8,
    changefreq="yearly",
)
@blueprint.get("/help/")
def help():
    return render_template("website/help.html")


@sitemapper.include(
    priority=0.6,
    changefreq="weekly",
    url_variables={
        "project_type": ["framework", "extension", "module", "project"],
    },
)
@blueprint.get("/<any(framework,extension,module,project,fulllist):project_type>/")
def projects(project_type):
    if project_type == "fulllist":
        projects = db.session.execute(db.select(Project)).all()
    else:
        projects = db.session.execute(db.select(Project).where(Project.category == project_type)).all()

    return render_template(
        "website/project_list.html",
        project_type=project_type,
        projects=projects,
    )


@sitemapper.include(
    priority=0.6,
    changefreq="weekly",
    url_variables={
        "slug": ["flask", "quart"],
    },
)
@blueprint.get("/about/<any(flask,quart):slug>/")
def get_project_info(slug):
    project = db.first_or_404(db.select(Project).where(Project.slug == slug))
    project = full_update_project_metadata(project=project)
    return render_template(f"website/{slug}_info.html", project=project)


@blueprint.get("/project/<slug>")
def get_project(slug):
    if slug in ["flask", "quart"]:
        return redirect(url_for("website.get_project_info", slug=slug), code=301)
    project = db.first_or_404(db.select(Project).where(Project.slug == slug))
    project = full_update_project_metadata(project=project)
    return render_template("website/project.html", project=project)


@sitemapper.include(
    priority=0.6,
    changefreq="weekly",
    url_variables={
        "slug": ["auth", "database", "api", "forms", "security", "frontend", "developer-tools"],
    },
)
@blueprint.get("/category/<slug>")
def get_tag(slug):
    tag = db.first_or_404(db.select(Tag).where(Tag.slug == slug))
    return render_template("website/tag.html", tag=tag)


@sitemapper.include(
    priority=1.0,
    changefreq="monthly",
)
@blueprint.route("/new-project/", methods=["GET"])
def new_project():
    form = NewProjectForm()
    return render_template("website/new_project.html", form=form)


@blueprint.route("/robots.txt", methods=["GET"])
def robok():
    robots = render_template("robots.txt")
    return Response(robots, mimetype="text/plain")


@blueprint.get("/sitemap.xml")
def full_sitemap():
    return sitemapper.generate()


@blueprint.get("/sitemap-projects.xml")
def project_sitemap():
    projects = db.session.execute(db.select(Project)).all()
    sitemap = render_template("sitemap.xml", projects=projects)
    return Response(sitemap, mimetype="application/xml")


@blueprint.get("tyn4pbqky6nwdz36cm33m343uga1pqv7.txt")
def index_now():
    return "tyn4pbqky6nwdz36cm33m343uga1pqv7"

limelight/templates/main.html
<!DOCTYPE html>
<html lang="{% block html_lang %}en{% endblock html_lang %}">

  <head>
    {% block head %}
    <script defer src="https://cloud.umami.is/script.js" data-website-id="cf71b793-a9a0-4d9d-9005-e2629a2ae39f"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>{% block title %}Flask Packages - Community-Driven Development for Flask Enthusiasts{% endblock title %}</title>

    {% block meta_content %}
    <meta name="description" content="Community-Driven Development for Flask Enthusiasts">
    <meta name="keywords" content="flask,extensions,project,python,development">
    <meta name="robots" content="index, follow">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="author" content="mariofix">
    <link rel="canonical" href="https://flaskpackages.pythonanywhere.com" />
    <meta property="og:title" content="Flask Packages">
    <meta property="og:site_name" content="Flask Packages">
    <meta property="og:url" content="https://flaskpackages.pythonanywhere.com" />
    <meta property="og:description" content="Community-Driven Development for Flask Enthusiasts">
    <meta property="og:type" content="website">

    {% endblock meta_content %}

    <meta name="google-site-verification" content="YQqBu9x3ym7UcbVCX3VBv-FQb1PI2FBQlYaopsj5Y80" />
    <meta name="msvalidate.01" content="3801A81CC043E6485E9A4113C491F7AA" />

    {% block favicon %}
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='apple-touch-icon.png', v=app_version)}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon-32x32.png', v=app_version)}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon-16x16.png', v=app_version)}}">
    <link rel="manifest" href="{{ url_for('static', filename='site.webmanifest', v=app_version)}}">
    {% endblock favicon %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">


    {% block post_css %}
    {% endblock post_css %}
    {% endblock head %}
  </head>

  <body>
    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('website.home') }}">
          <i class="bi bi-cassette me-2"></i> Limelight
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('website.home') }}">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="discoverDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Discover
              </a>
              <ul class="dropdown-menu" aria-labelledby="discoverDropdown">
                <li><a class="dropdown-item" href="{{ url_for('website.projects', project_type='framework') }}">Frameworks</a></li>
                <li><a class="dropdown-item" href="{{ url_for('website.projects', project_type='extension') }}">Extension</a></li>
                <li><a class="dropdown-item" href="{{ url_for('website.projects', project_type='module') }}">Modules</a></li>
                <li><a class="dropdown-item" href="{{ url_for('website.projects', project_type='project') }}">Projects/Applications</a></li>
                <li><a class="dropdown-item" href="{{ url_for('website.projects', project_type='fulllist') }}">Show All</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('website.new_project') }}">Submit a Project</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('website.help') }}">Help</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    {% block content %}

    {% endblock content %}


    {% block footer %}
    <!-- Footer -->
    <footer class="footer mt-auto bg-dark py-3 text-white text-center">

      <div class="container">
        <p>Limelight - Find the Flask Extension you were not looking for.</p>
        <div>
          <a href="https://github.com/mariofix/limelight" class="text-white mx-2">Source Code</a>
        </div>
      </div>
    </footer>
    {% endblock footer %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block post_js %}
    {% endblock post_js %}
  </body>

</html>